project_name: satnet-mirror-detection
run_name: swin-s-msd-512

data_root: "/Users/ijeongmin/🔥이정민🔥/가천대학교/CVIP/Mirror Detect/Dataset/MSD"
img_size: 512
batch_size: 2
num_workers: 0

backbone: swin_small_patch4_window7_224
pretrained: true

num_epochs: 10
lr: 0.0006
betas: [0.9, 0.999]
weight_decay: 0.01
loss_weights: [1.25, 1.25, 1.0, 1.5]

log_interval: 20
save_dir: "./checkpoints"