# -*- coding: utf-8 -*-
"""SATNet_execution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k_My0lOuHigg6XV_b80Xg6hTPcgEBGNP
"""

from google.colab import drive
drive.mount("/content/drive", force_remount=True)

import os

base = "/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/Mirror/SATNet"
print(os.path.exists(base))
print(os.listdir(base)[:10])

"""## Preparing Datasets"""

!mkdir -p /content/datasets
!tar --warning=no-unknown-keyword -xf "/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/Mirror/Dataset/MSD.tar" -C /content/datasets

!find /content/datasets/MSD -maxdepth 2 -type d | sort
!find /content/datasets/MSD/train/image -type f | wc -l
!find /content/datasets/MSD/train/mask -type f | wc -l
!find /content/datasets/MSD/test/image -type f | wc -l
!find /content/datasets/MSD/test/mask -type f | wc -l

!find /content/datasets/MSD -name "._*" | head
!find /content/datasets/MSD -name "._*" | wc -l

!find /content/datasets/MSD -name "._*" -type f -delete
!find /content/datasets/MSD -type d -name "__MACOSX" -prune -exec rm -rf {} +

!find /content/datasets/MSD/train/image -type f | wc -l
!find /content/datasets/MSD/train/mask -type f | wc -l
!find /content/datasets/MSD/test/image -type f | wc -l
!find /content/datasets/MSD/test/mask -type f | wc -l

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/Mirror/SATNet"

from sample_network_edited import SAAM, CFDM, TrainableSATNetWithSwinEdited

import timm
import random
import os
import glob
import cv2
import math
import numpy as np
from tqdm import tqdm
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, Subset
import torchvision.transforms as T
import torch.nn.functional as F
from sample_network_edited import SAAM, CFDM, TrainableSATNetWithSwinEdited

import yaml

try:
    import wandb
except ImportError:
    wandb = None

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def load_config(config_path=None):
    if config_path is None:
        config_path = "config_final.yaml"

    with open(config_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)

config = load_config()

use_wandb = config.get("use_wandb", False)

root = config.get("data_root", "/content/datasets/MSD")
#root = "/content/datasets/MSD"

def apply_photometric_distortion(image):
    image = image.astype(np.float32)

    if random.random() < 0.5:
        image += random.uniform(-32, 32)
    if random.random() < 0.5:
        image *= random.uniform(0.5, 1.5)

    image = np.clip(image, 0, 255).astype(np.uint8)

    if random.random() < 0.5:
        hsv = cv2.cvtColor(image, cv2.COLOR_RGB2HSV).astype(np.float32)
        hsv[..., 1] *= random.uniform(0.5, 1.5)
        hsv[..., 0] += random.uniform(-18, 18)
        hsv[..., 0] = np.mod(hsv[..., 0], 180)
        hsv[..., 1:] = np.clip(hsv[..., 1:], 0, 255)
        image = cv2.cvtColor(hsv.astype(np.uint8), cv2.COLOR_HSV2RGB)

    return image

class MirrorDataset(Dataset):
    def __init__(self, img_dir: str, mask_dir: str, size: int = 512, is_train=False, augment=False, base_scale=520, crop_size=None, ratio_range=(0.5, 2.0), flip_prob=0.5, photometric_distortion=True, cat_max_ratio=0.75, ignore_index=255):
        self.img_paths = sorted(glob.glob(os.path.join(img_dir, "*.jpg")))
        self.mask_dir = mask_dir
        self.size = int(size)
        self.is_train = is_train
        self.augment = augment
        self.base_scale = int(base_scale)
        self.crop_size = int(crop_size or size)
        self.ratio_range = tuple(ratio_range)
        self.flip_prob = float(flip_prob)
        self.photometric_distortion = photometric_distortion
        self.cat_max_ratio = float(cat_max_ratio)
        self.ignore_index = int(ignore_index)

    def __len__(self):
        return len(self.img_paths)

    def _random_resize(self, image, mask):
        h, w = image.shape[:2]
        ratio = random.uniform(*self.ratio_range)
        target_short = max(1, int(self.base_scale * ratio))
        scale = target_short / min(h, w)

        new_h = max(1, int(round(h*scale)))
        new_w = max(1, int(round(w*scale)))

        image = cv2.resize(image, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
        mask = cv2.resize(mask, (new_w, new_h), interpolation=cv2.INTER_NEAREST)

        return image, mask

    def _pad_if_needed(self, image, mask):
        h, w = image.shape[:2]
        pad_h = max(self.crop_size - h, 0)
        pad_w = max(self.crop_size - w, 0)

        if pad_h > 0 or pad_w > 0:
            image = cv2.copyMakeBorder(image, 0, pad_h, 0, pad_w, borderType=cv2.BORDER_CONSTANT, value=(0, 0, 0))
            mask = cv2.copyMakeBorder(mask, 0, pad_h, 0, pad_w, borderType=cv2.BORDER_CONSTANT, value=self.ignore_index,)

        return image, mask

    def _random_crop(self, image, mask):
        image, mask = self._pad_if_needed(image, mask)
        h, w = image.shape[:2]

        best_top = random.randint(0, h - self.crop_size)
        best_left = random.randint(0, w - self.crop_size)

        for _ in range(10):
            top = random.randint(0, h - self.crop_size)
            left = random.randint(0, w - self.crop_size)
            crop_mask = mask[top:top+self.crop_size, left:left+self.crop_size]

            valid = crop_mask != self.ignore_index
            if valid.any():
                _, counts = np.unique(crop_mask[valid], return_counts=True)
                if counts.max() / counts.sum() < self.cat_max_ratio:
                    best_top, best_left = top, left
                    break

            best_top, best_left = top, left

        image = image[best_top:best_top+self.crop_size, best_left:best_left+self.crop_size]
        mask = mask[best_top:best_top+self.crop_size, best_left:best_left+self.crop_size]
        return image, mask

    def __getitem__(self, idx):
        img_path = self.img_paths[idx]
        name = os.path.basename(img_path).replace(".jpg", ".png")
        mask_path = os.path.join(self.mask_dir, name)

        image_bgr = cv2.imread(img_path)
        mask = cv2.imread(mask_path, cv2.IMREAD_GRAYSCALE)

        if image_bgr is None:
            raise FileNotFoundError(f"Image load failed: {img_path}")
        if mask is None:
            raise FileNotFoundError(f"Mask load failed: {mask_path}")

        image = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
        mask = (mask > 127).astype(np.uint8)

        if self.is_train and self.augment:
            image, mask = self._random_resize(image, mask)
            image, mask = self._random_crop(image, mask)

            if random.random() < self.flip_prob:
                image = cv2.flip(image, 1)
                mask = cv2.flip(mask, 1)

            if self.photometric_distortion:
                image = apply_photometric_distortion(image)
        else:
            image = cv2.resize(image, (self.size, self.size), interpolation=cv2.INTER_LINEAR)
            mask = cv2.resize(mask, (self.size, self.size), interpolation=cv2.INTER_NEAREST)
            # mask는 일반 이미지가 아니라 class label map이기 때문에 INTER_NEAREST 사용해야함.
            # bilinear interpolate로 resize하면 중간값이 생긴다.

        image = np.ascontiguousarray(image)
        mask = np.ascontiguousarray(mask)

        image = torch.from_numpy(image).float().permute(2, 0, 1) / 255.0
        mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
        std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)
        image = (image - mean) / std

        mask = torch.from_numpy(mask).long()

        return image, mask

class SwinTBackbone_T(nn.Module):
    def __init__(self, img_size=256, pretrained=False):
        super().__init__()
        self.backbone = timm.create_model(
            "swin_tiny_patch4_window7_224",
            pretrained=pretrained,
            features_only=True,
            out_indices=(0, 1, 2, 3),
            img_size = img_size,
        )

    def forward(self, x):
        features = self.backbone(x)
        features = [f.permute(0, 3, 1, 2).contiguous() for f in features]
        return features

class SwinTBackbone_S(nn.Module):
    def __init__(self, img_size=512, pretrained=False):
        super().__init__()
        self.backbone = timm.create_model(
            "swin_small_patch4_window7_224",
            pretrained=pretrained,
            features_only=True,
            out_indices=(0, 1, 2, 3),
            img_size = img_size,
        )

    def forward(self, x):
        features = self.backbone(x)
        features = [f.permute(0, 3, 1, 2).contiguous() for f in features]
        return features

class TrainableSATNetWithSwin(nn.Module):
    def __init__(self, img_size=256, pretrained=False):
        super().__init__()

        self.encoder = SwinTBackbone_S(img_size=img_size, pretrained=pretrained)

        self.saam2 = SAAM(embed_dim=384, num_heads=12)
        self.saam3 = SAAM(embed_dim=768, num_heads=24)

        self.cfdm3 = CFDM(channels=768, stage=3)
        self.cfdm2 = CFDM(channels=384, stage=2, prev_channels=768)
        self.cfdm1 = CFDM(channels=192, stage=1, prev_channels=384)
        self.cfdm0 = CFDM(channels=96, stage=0, prev_channels=192)

        self.seg_head0 = nn.Conv2d(96, 2, kernel_size=1)
        self.seg_head1 = nn.Conv2d(192, 2, kernel_size=1)
        self.seg_head2 = nn.Conv2d(384, 2, kernel_size=1)
        self.seg_head3 = nn.Conv2d(768, 2, kernel_size=1)

    def forward(self, x):
        x_flip = torch.flip(x, dims=[-1])

        f0, f1, f2, f3 = self.encoder(x)
        ff0, ff1, ff2, ff3 = self.encoder(x_flip)

        ff0 = torch.flip(ff0, dims=[-1])
        ff1 = torch.flip(ff1, dims=[-1])

        f2, ff2 = self.saam2(f2, ff2)
        f3, ff3 = self.saam3(f3, ff3)

        out3 = self.cfdm3(f3, ff3)
        out2 = self.cfdm2(f2, ff2, prev_output=out3)
        out1 = self.cfdm1(f1, ff1, prev_output=out2)
        out0 = self.cfdm0(f0, ff0, prev_output=out1)

        p3 = self.seg_head3(out3)
        p2 = self.seg_head2(out2)
        p1 = self.seg_head1(out1)
        p0 = self.seg_head0(out0)

        return [p0, p1, p2, p3]

def set_seed(seed):
    random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)

set_seed(int(config.get("seed", 42)))

#root = config.get("data_root", "/content/datasets/MSD")
root = "/content/datasets/MSD"
if root.endswith((".tar", ".tar.gz", ".zip")):
    raise ValueError("data_root는 압축파일이 아니라 /content/datasets/MSD 같은 압축 해제 폴더여야 합니다.")

# full_train_dataset = MirrorDataset(f"{root}/train/image", f"{root}/train/mask", size=config["img_size"])
# test_dataset = MirrorDataset(f"{root}/test/image", f"{root}/test/mask", size=config["img_size"])

# val_ratio = float(config.get("val_ratio", 0.1))

ignore_index = int(config.get("ignore_index", 255))
ratio_range = tuple(config.get("ratio_range", [0.5, 2.0]))
crop_size = int(config.get("crop_size", config["img_size"]))

train_img_dir = f"{root}/train/image"
train_mask_dir = f"{root}/train/mask"
test_img_dir = f"{root}/test/image"
test_mask_dir = f"{root}/test/mask"

train_aug_dataset = MirrorDataset(
    train_img_dir,
    train_mask_dir,
    size=config["img_size"],
    is_train=True,
    augment=bool(config.get("augment", True)),
    base_scale=config.get("base_scale", 520),
    crop_size=crop_size,
    ratio_range = ratio_range,
    flip_prob = config.get("flip_prob", 0.5),
    photometric_distortion = config.get("photometric_distortion", True),
    cat_max_ratio = config.get("cat_max_ratio", 0.75),
    ignore_index=ignore_index
)

train_eval_dataset = MirrorDataset(
    train_img_dir,
    train_mask_dir,
    size=config["img_size"],
    is_train=False,
    augment=False,
    ignore_index=ignore_index,
)

test_dataset = MirrorDataset(
    test_img_dir,
    test_mask_dir,
    size=config["img_size"],
    is_train=False,
    augment=False,
    ignore_index=ignore_index,
)

val_ratio = float(config.get("val_ratio", 0.1))
generator = torch.Generator().manual_seed(int(config.get("seed", 42)))


if val_ratio > 0:
    n_total = len(train_aug_dataset)
    val_size = min(max(1, int(n_total * val_ratio)), n_total - 1)
    indices = torch.randperm(n_total, generator=generator).tolist()

    val_indices = indices[:val_size]
    train_indices = indices[val_size:]

    train_dataset = Subset(train_aug_dataset, train_indices)
    val_dataset = Subset(train_eval_dataset, val_indices)
else:
    train_dataset = train_aug_dataset
    #val_dataset = test_dataset
    val_dataset = None

val_len = len(val_dataset) if val_dataset is not None else 0
print(f"train: {len(train_dataset)}, val: {val_len}, test: {len(test_dataset)}")

pin_memory = bool(config.get("pin_memory", False)) and device.type == "cuda"

# train_loader = DataLoader(train_dataset, batch_size=config["batch_size"], shuffle=True,
#                           num_workers=config["num_workers"], pin_memory=pin_memory)
# val_loader = DataLoader(val_dataset, batch_size=config["batch_size"], shuffle=False,
#                         num_workers=config["num_workers"], pin_memory=pin_memory)
# test_loader = DataLoader(test_dataset, batch_size=config["batch_size"], shuffle=False,
#                          num_workers=config["num_workers"], pin_memory=pin_memory)

train_loader = DataLoader(train_dataset, batch_size=config["batch_size"], shuffle=True,
                          num_workers=config["num_workers"], pin_memory=pin_memory)

val_loader = None
if val_dataset is not None:
    val_loader = DataLoader(val_dataset, batch_size=config["batch_size"], shuffle=False,
                            num_workers=config["num_workers"], pin_memory=pin_memory)

test_loader = DataLoader(test_dataset, batch_size=config["batch_size"], shuffle=False,
                         num_workers=config["num_workers"], pin_memory=pin_memory)

val_len = len(val_dataset) if val_dataset is not None else 0
print(f"train: {len(train_dataset)}, val: {val_len}, test: {len(test_dataset)}")

model = TrainableSATNetWithSwinEdited(img_size=config["img_size"],pretrained=config["pretrained"], fusion_mode = config.get("fusion_mode", "gated_add")).to(device)
optimizer = torch.optim.AdamW(model.parameters(),lr=config["lr"],betas=tuple(config["betas"]),weight_decay=config["weight_decay"],)

ignore_index=int(config.get("ignore_index", 255))
criterion = nn.CrossEntropyLoss(ignore_index=ignore_index)

def satnet_loss(preds, mask, weights):
    total_loss = torch.zeros((), device=mask.device)

    for pred, weight in zip(preds, weights):
        pred = F.interpolate(
            pred,
            size=mask.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )
        total_loss = total_loss + weight * criterion(pred, mask)

    return total_loss

# num_epochs = int(config["num_epochs"])
# total_iters = max(1, num_epochs * len(train_loader))
accumulation_steps = int(config.get("accumulation_steps", 1))
max_iters = int(config.get("max_iters", 0))

if max_iters > 0:
    total_iters = max_iters  # optimizer update 기준
    total_micro_iters = total_iters * accumulation_steps
    num_epochs = math.ceil(total_micro_iters / len(train_loader))
else:
    num_epochs = int(config["num_epochs"])
    total_micro_iters = num_epochs * len(train_loader)
    total_iters = math.ceil(total_micro_iters / accumulation_steps)

def poly_lr_lambda(current_iter):
    return max(0.0, 1.0 - current_iter / total_iters)

scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda=poly_lr_lambda)
print(
    f"batch_size={config['batch_size']}, "
    f"accumulation_steps={accumulation_steps}, "
    f"effective_batch={config['batch_size'] * accumulation_steps}, "
    f"optimizer_updates={total_iters}, "
    f"micro_batches={total_micro_iters}, "
    f"num_epochs={num_epochs}"
)

# def metric_sums(logits, mask, threshold=0.5, eps=1e-7):
#     logits = F.interpolate(logits, size=mask.shape[-2:], mode="bilinear", align_corners=False)
#     prob = torch.softmax(logits, dim=1)[:, 1]
#     gt = (mask > 0).float()
#     pred = (prob > threshold).float()

#     dims = (1, 2)
#     inter = (pred * gt).sum(dim=dims)
#     union = pred.sum(dim=dims) + gt.sum(dim=dims) - inter

#     iou = torch.where(union > 0, inter / (union + eps), torch.ones_like(union))

#     tp = inter
#     fp = (pred * (1 - gt)).sum(dim=dims)
#     fn = ((1 - pred) * gt).sum(dim=dims)
#     f = torch.where((2 * tp + fp + fn) > 0, (2 * tp) / (2 * tp + fp + fn + eps), torch.ones_like(tp))

#     mae = torch.abs(prob - gt).mean(dim=dims)

#     return iou.sum().item(), f.sum().item(), mae.sum().item(), mask.size(0)

def update_eval_metrics(state, logits, mask):
    ignore_index = int(config.get("ignore_index", 255))
    beta_square = float(config.get("f_beta_square", 0.3))
    num_thresholds = int(config.get("metric_num_thresholds", 256))
    eps = 1e-7

    logits = F.interpolate(logits, size=mask.shape[-2:], mode="bilinear", align_corners=False)
    prob = torch.softmax(logits, dim=1)[:, 1]

    thresholds = torch.linspace(0, 1, num_thresholds, device=prob.device)

    for b in range(prob.size(0)):
        valid = mask[b] != ignore_index
        if valid.sum() == 0:
            continue

        p = prob[b][valid]
        g = (mask[b][valid] > 0).float()
        g_bool = g.bool()

        hard_05 = p > 0.5
        inter = (hard_05 & g_bool).sum().float()
        union = hard_05.sum().float() + g_bool.sum().float() - inter
        iou = inter / (union + eps) if union > 0 else torch.tensor(0.0, device=prob.device)

        mae = torch.abs(p - g).mean()

        hard = p.unsqueeze(0) > thresholds.unsqueeze(1)
        tp = (hard & g_bool.unsqueeze(0)).sum(dim=1).float()
        pred_sum = hard.sum(dim=1).float()
        gt_sum = g_bool.sum().float()

        precision = (tp + eps) / (pred_sum + eps)
        recall = (tp + eps) / (gt_sum + eps)

        state["iou_sum"] += iou.item()
        state["mae_sum"] += mae.item()
        state["precision_sum"] += precision.detach().cpu()
        state["recall_sum"] += recall.detach().cpu()
        state["count"] += 1


def evaluate(model, loader, desc="Val"):
    model.eval()

    num_thresholds = int(config.get("metric_num_thresholds", 256))
    beta_square = float(config.get("f_beta_square", 0.3))
    eps = 1e-7

    state = {
        "loss_sum": 0.0,
        "loss_count": 0,
        "iou_sum": 0.0,
        "mae_sum": 0.0,
        "precision_sum": torch.zeros(num_thresholds),
        "recall_sum": torch.zeros(num_thresholds),
        "count": 0,
    }

    with torch.no_grad():
        for image, mask in tqdm(loader, desc=desc, leave=False):
            image = image.to(device)
            mask = mask.to(device)

            preds = model(image)
            loss = satnet_loss(preds, mask, config["loss_weights"])

            bs = image.size(0)
            state["loss_sum"] += loss.item() * bs
            state["loss_count"] += bs

            update_eval_metrics(state, preds[0], mask)

    count = max(state["count"], 1)
    precision = state["precision_sum"] / count
    recall = state["recall_sum"] / count

    f_beta = (1 + beta_square) * precision * recall / (beta_square * precision + recall + eps)
    max_f_beta = f_beta.max().item()

    return {
        "loss": state["loss_sum"] / max(state["loss_count"], 1),
        "iou": state["iou_sum"] / count,
        "f": max_f_beta,
        "mae": state["mae_sum"] / count,
    }

def save_checkpoint(path, epoch, global_step, best_score, best_iou):
    torch.save({
        "epoch": epoch,
        "global_step": global_step,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "scheduler_state_dict": scheduler.state_dict(),
        "best_score": best_score,
        "best_iou": best_iou,
        "config": config,
    }, path)

save_dir = config["save_dir"]
os.makedirs(save_dir, exist_ok=True)

start_epoch = 0
global_step = 0
best_metric = str(config.get("best_metric", "iou")).lower()
best_score = float("inf") if best_metric == "mae" else -float("inf")
best_iou = -float("inf")

resume = bool(config.get("resume", False))
resume_path = config.get("resume_path", os.path.join(save_dir, "last_model.pth"))

if resume and os.path.exists(resume_path):
    print(f"Resuming from checkpoint: {resume_path}")

    ckpt = torch.load(resume_path, map_location=device)

    model.load_state_dict(ckpt["model_state_dict"])

    if "optimizer_state_dict" in ckpt:
        optimizer.load_state_dict(ckpt["optimizer_state_dict"])

    if "scheduler_state_dict" in ckpt:
        scheduler.load_state_dict(ckpt["scheduler_state_dict"])

    start_epoch = int(ckpt.get("epoch", 0))
    global_step = int(ckpt.get("global_step", 0))
    best_score = float(ckpt.get("best_score", best_score))
    best_iou = float(ckpt.get("best_iou", best_iou))

    print(
        f"Resume success: next_epoch={start_epoch + 1}, "
        f"global_step={global_step}, best_iou={best_iou:.4f}"
    )
else:
    print("No checkpoint resume. Training from scratch.")

import os
import glob

print("save_dir:")
print(save_dir)

print("\nresume:")
print(resume)

print("\nresume_path:")
print(resume_path)

print("\nresume_path exists:")
print(os.path.exists(resume_path))

print("\nfiles in save_dir:")
for p in sorted(glob.glob(os.path.join(save_dir, "*.pth"))):
    print(p)

print("\npossible SATNet checkpoint folders:")
for d in sorted(glob.glob("/content/drive/MyDrive/Colab Notebooks/CVIP_LAB/Mirror/SATNet/checkpoints*")):
    print(d)

if use_wandb and wandb is not None:
    wandb.login()
    wandb.init(project=config["project_name"], name=config["run_name"], config=config)

micro_step = global_step * accumulation_steps
optimizer.zero_grad(set_to_none=True)

for epoch in range(start_epoch, num_epochs):
    model.train()
    train_loss_sum, train_seen = 0.0, 0

    progress_bar = tqdm(train_loader, desc=f"Epoch {epoch + 1}/{num_epochs}")

    for image, mask in progress_bar:
        if global_step >= total_iters:
            break

        image = image.to(device)
        mask = mask.to(device)

        preds = model(image)
        raw_loss = satnet_loss(preds, mask, config["loss_weights"])
        loss = raw_loss / accumulation_steps

        loss.backward()

        bs = image.size(0)
        train_loss_sum += raw_loss.item() * bs
        train_seen += bs
        micro_step += 1

        if micro_step % accumulation_steps == 0:
            optimizer.step()
            scheduler.step()
            optimizer.zero_grad(set_to_none=True)
            global_step += 1

        lr = scheduler.get_last_lr()[0]
        progress_bar.set_postfix(
            loss=f"{raw_loss.item():.4f}",
            lr=f"{lr:.6f}",
            update=global_step,
            micro=micro_step,
        )

        if global_step >= total_iters:
            break

    train_loss = train_loss_sum / max(train_seen, 1)

    if val_loader is not None:
        val = evaluate(model, val_loader, desc=f"Val {epoch + 1}/{num_epochs}")

        best_iou = max(best_iou, val["iou"])
        score = val[best_metric]
        is_best = score < best_score if best_metric == "mae" else score > best_score

        if is_best:
            best_score = score
            save_checkpoint(
                os.path.join(save_dir, "best_model.pth"),
                epoch + 1,
                global_step,
                best_score,
                best_iou,
            )

        val_loss = val["loss"]
        val_iou = val["iou"]
        val_f = val["f"]
        val_mae = val["mae"]
    else:
        val_loss = float("nan")
        val_iou = float("nan")
        val_f = float("nan")
        val_mae = float("nan")

    save_checkpoint(
        os.path.join(save_dir, "last_model.pth"),
        epoch + 1,
        global_step,
        best_score,
        best_iou,
    )

    if (epoch + 1) % config.get("save_interval", 1) == 0:
        save_checkpoint(
            os.path.join(save_dir, f"satnet_epoch_{epoch + 1}.pth"),
            epoch + 1,
            global_step,
            best_score,
            best_iou,
        )

    lr = scheduler.get_last_lr()[0]
    print(
        f"epoch={epoch + 1}/{num_epochs} "
        f"train_loss={train_loss:.4f} val_loss={val_loss:.4f} "
        f"val_IoU={val_iou:.4f} val_F={val_f:.4f} val_MAE={val_mae:.4f} "
        f"best_IoU={best_iou:.4f} lr={lr:.6f} "
        f"update={global_step}/{total_iters}",
        flush=True,
    )

    if use_wandb and wandb is not None:
        log_dict = {
            "train/loss": train_loss,
            "lr": lr,
            "epoch": epoch + 1,
            "global_step": global_step,
            "micro_step": micro_step,
            "effective_batch_size": config["batch_size"] * accumulation_steps,
        }

        if val_loader is not None:
            log_dict.update({
                "val/loss": val_loss,
                "val/iou": val_iou,
                "val/f": val_f,
                "val/mae": val_mae,
                "best/iou": best_iou,
            })

        wandb.log(log_dict, step=global_step)

    if global_step >= total_iters:
        break

# if use_wandb and wandb is not None:
#     wandb.finish()

"""# Test"""

if val_loader is not None and os.path.exists(os.path.join(save_dir, "best_model.pth")):
    eval_path = os.path.join(save_dir, "best_model.pth")
else:
    eval_path = os.path.join(save_dir, "last_model.pth")

print(f"Loading checkpoint for final test: {eval_path}")

ckpt = torch.load(eval_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()

test = evaluate(model, test_loader, desc="Final Test")
print(
    f"[Final Test] IoU={test['iou']:.4f} F={test['f']:.4f} MAE={test['mae']:.4f} loss={test['loss']:.4f}",
    flush=True,
)

if use_wandb and wandb is not None:
    wandb.log({
        "test/loss": test["loss"],
        "test/iou": test["iou"],
        "test/f": test["f"],
        "test/mae": test["mae"],
    }, step=global_step)
    wandb.finish()

"""# Test w/o Wandb"""

import os
import torch

if val_loader is not None and os.path.exists(os.path.join(save_dir, "best_model.pth")):
    eval_path = os.path.join(save_dir, "best_model.pth")
else:
    eval_path = os.path.join(save_dir, "last_model.pth")

print(f"Loading checkpoint for final test: {eval_path}")

ckpt = torch.load(eval_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()

test = evaluate(model, test_loader, desc="Final Test")

print(
    f"[Final Test] IoU={test['iou']:.4f} "
    f"F={test['f']:.4f} "
    f"MAE={test['mae']:.4f} "
    f"loss={test['loss']:.4f}",
    flush=True,
)

"""# Eval each head"""

import os
import torch
import torch.nn.functional as F
import pandas as pd
from tqdm import tqdm

# checkpoint load
if val_loader is not None and os.path.exists(os.path.join(save_dir, "best_model.pth")):
    eval_path = os.path.join(save_dir, "best_model.pth")
else:
    eval_path = os.path.join(save_dir, "last_model.pth")

print(f"Loading checkpoint: {eval_path}")

ckpt = torch.load(eval_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()


@torch.no_grad()
def evaluate_single_head(model, loader, head_idx=0, desc="Test"):
    model.eval()

    num_thresholds = int(config.get("metric_num_thresholds", 256))
    beta_square = float(config.get("f_beta_square", 0.3))
    ignore_index = int(config.get("ignore_index", 255))
    eps = 1e-7

    state = {
        "loss_sum": 0.0,
        "loss_count": 0,
        "iou_sum": 0.0,
        "mae_sum": 0.0,
        "precision_sum": torch.zeros(num_thresholds),
        "recall_sum": torch.zeros(num_thresholds),
        "count": 0,
    }

    thresholds = torch.linspace(0, 1, num_thresholds, device=device)

    for image, mask in tqdm(loader, desc=f"{desc} head={head_idx}", leave=False):
        image = image.to(device)
        mask = mask.to(device)

        preds = model(image)
        logits = preds[head_idx]

        logits = F.interpolate(
            logits,
            size=mask.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

        loss = criterion(logits, mask)

        bs = image.size(0)
        state["loss_sum"] += loss.item() * bs
        state["loss_count"] += bs

        prob = torch.softmax(logits, dim=1)[:, 1]

        for b in range(prob.size(0)):
            valid = mask[b] != ignore_index
            if valid.sum() == 0:
                continue

            p = prob[b][valid]
            g = (mask[b][valid] > 0).float()
            g_bool = g.bool()

            hard_05 = p > 0.5
            inter = (hard_05 & g_bool).sum().float()
            union = hard_05.sum().float() + g_bool.sum().float() - inter
            iou = inter / (union + eps) if union > 0 else torch.tensor(0.0, device=device)

            mae = torch.abs(p - g).mean()

            hard = p.unsqueeze(0) > thresholds.unsqueeze(1)
            tp = (hard & g_bool.unsqueeze(0)).sum(dim=1).float()
            pred_sum = hard.sum(dim=1).float()
            gt_sum = g_bool.sum().float()

            precision = (tp + eps) / (pred_sum + eps)
            recall = (tp + eps) / (gt_sum + eps)

            state["iou_sum"] += iou.item()
            state["mae_sum"] += mae.item()
            state["precision_sum"] += precision.detach().cpu()
            state["recall_sum"] += recall.detach().cpu()
            state["count"] += 1

    count = max(state["count"], 1)
    precision = state["precision_sum"] / count
    recall = state["recall_sum"] / count

    f_beta = (1 + beta_square) * precision * recall / (
        beta_square * precision + recall + eps
    )

    return {
        "head": f"p{head_idx}",
        "loss": state["loss_sum"] / max(state["loss_count"], 1),
        "iou": state["iou_sum"] / count,
        "f": f_beta.max().item(),
        "mae": state["mae_sum"] / count,
        "best_threshold": (torch.argmax(f_beta).item() / max(num_thresholds - 1, 1)),
    }


results = []
for head_idx in range(4):
    results.append(evaluate_single_head(model, test_loader, head_idx=head_idx, desc="Final Test"))

df = pd.DataFrame(results)
df = df[["head", "iou", "f", "mae", "loss", "best_threshold"]]
df

"""# Visualization"""

import os
import random
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F

best_path = os.path.join(save_dir, "best_model.pth")
last_path = os.path.join(save_dir, "last_model.pth")

eval_path = best_path if os.path.exists(best_path) else last_path

print(f"Loading checkpoint for visualization: {eval_path}")

ckpt = torch.load(eval_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()

vis_dir = os.path.join(save_dir, "visualizations")
os.makedirs(vis_dir, exist_ok=True)

mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

indices = random.sample(range(len(test_dataset)), 10)

for n, idx in enumerate(indices, start=1):
    image, mask = test_dataset[idx]

    with torch.no_grad():
        x = image.unsqueeze(0).to(device)
        preds = model(x)
        logits = F.interpolate(
            preds[0],
            size=mask.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )
        prob = torch.softmax(logits, dim=1)[0, 1].cpu().numpy()

    img = (image.cpu() * std + mean).clamp(0, 1)
    img = img.permute(1, 2, 0).numpy()

    gt = mask.cpu().numpy()
    pred = (prob >= 0.5).astype(np.uint8)

    overlay = img.copy()
    overlay[..., 0] = np.maximum(overlay[..., 0], pred * 1.0)

    fig, axes = plt.subplots(1, 4, figsize=(16, 4))

    axes[0].imshow(img)
    axes[0].set_title("Image")
    axes[0].axis("off")

    axes[1].imshow(gt, cmap="gray")
    axes[1].set_title("GT")
    axes[1].axis("off")

    axes[2].imshow(prob, cmap="gray", vmin=0, vmax=1)
    axes[2].set_title("Pred Prob")
    axes[2].axis("off")

    # axes[3].imshow(overlay)
    # axes[3].set_title("Overlay")
    # axes[3].axis("off")

    axes[3].imshow(pred, cmap="gray", vmin=0, vmax=1)
    axes[3].set_title("Pred Mask @0.5")
    axes[3].axis("off")

    plt.tight_layout()

    out_path = os.path.join(vis_dir, f"sample_{n}.png")
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.show()

    print(f"saved: {out_path}")

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F

@torch.no_grad()
def inspect_prediction_stats(model, dataset, n=12):
    model.eval()
    rows = []

    indices = np.linspace(0, len(dataset) - 1, n, dtype=int)

    for idx in indices:
        image, mask = dataset[idx]

        x = image.unsqueeze(0).to(device)
        logits = model(x)[0]
        logits = F.interpolate(
            logits,
            size=mask.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

        prob = torch.softmax(logits, dim=1)[0, 1].cpu()
        gt = mask.cpu()

        valid = gt != 255
        prob_v = prob[valid]
        gt_v = gt[valid].float()

        pred_05 = (prob_v >= 0.5).float()
        pred_03 = (prob_v >= 0.3).float()
        pred_01 = (prob_v >= 0.1).float()

        inter = ((pred_05 == 1) & (gt_v == 1)).sum().item()
        union = ((pred_05 == 1) | (gt_v == 1)).sum().item()
        iou_05 = inter / max(union, 1)

        rows.append({
            "idx": idx,
            "gt_fg_ratio": gt_v.mean().item(),
            "prob_min": prob_v.min().item(),
            "prob_mean": prob_v.mean().item(),
            "prob_max": prob_v.max().item(),
            "pred_fg@0.5": pred_05.mean().item(),
            "pred_fg@0.3": pred_03.mean().item(),
            "pred_fg@0.1": pred_01.mean().item(),
            "IoU@0.5": iou_05,
        })

    return pd.DataFrame(rows)

inspect_prediction_stats(model, test_dataset, n=12)

"""# Visualization w/ best head"""

import os
import torch
import torch.nn.functional as F
from tqdm import tqdm

head_idx = 2

if val_loader is not None and os.path.exists(os.path.join(save_dir, "best_model.pth")):
    eval_path = os.path.join(save_dir, "best_model.pth")
else:
    eval_path = os.path.join(save_dir, "last_model.pth")

print(f"Loading checkpoint for p{head_idx} final test: {eval_path}")

ckpt = torch.load(eval_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()


@torch.no_grad()
def evaluate_head(model, loader, head_idx=2, desc="Final Test"):
    model.eval()

    num_thresholds = int(config.get("metric_num_thresholds", 256))
    beta_square = float(config.get("f_beta_square", 0.3))
    ignore_index = int(config.get("ignore_index", 255))
    eps = 1e-7

    state = {
        "loss_sum": 0.0,
        "loss_count": 0,
        "iou_sum": 0.0,
        "mae_sum": 0.0,
        "precision_sum": torch.zeros(num_thresholds),
        "recall_sum": torch.zeros(num_thresholds),
        "count": 0,
    }

    thresholds = torch.linspace(0, 1, num_thresholds, device=device)

    for image, mask in tqdm(loader, desc=f"{desc} p{head_idx}", leave=False):
        image = image.to(device)
        mask = mask.to(device)

        preds = model(image)
        logits = preds[head_idx]

        logits = F.interpolate(
            logits,
            size=mask.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

        loss = criterion(logits, mask)

        bs = image.size(0)
        state["loss_sum"] += loss.item() * bs
        state["loss_count"] += bs

        prob = torch.softmax(logits, dim=1)[:, 1]

        for b in range(prob.size(0)):
            valid = mask[b] != ignore_index
            if valid.sum() == 0:
                continue

            p = prob[b][valid]
            g = (mask[b][valid] > 0).float()
            g_bool = g.bool()

            hard_05 = p > 0.5
            inter = (hard_05 & g_bool).sum().float()
            union = hard_05.sum().float() + g_bool.sum().float() - inter
            iou = inter / (union + eps) if union > 0 else torch.tensor(0.0, device=device)

            mae = torch.abs(p - g).mean()

            hard = p.unsqueeze(0) > thresholds.unsqueeze(1)
            tp = (hard & g_bool.unsqueeze(0)).sum(dim=1).float()
            pred_sum = hard.sum(dim=1).float()
            gt_sum = g_bool.sum().float()

            precision = (tp + eps) / (pred_sum + eps)
            recall = (tp + eps) / (gt_sum + eps)

            state["iou_sum"] += iou.item()
            state["mae_sum"] += mae.item()
            state["precision_sum"] += precision.detach().cpu()
            state["recall_sum"] += recall.detach().cpu()
            state["count"] += 1

    count = max(state["count"], 1)
    precision = state["precision_sum"] / count
    recall = state["recall_sum"] / count

    f_beta = (1 + beta_square) * precision * recall / (
        beta_square * precision + recall + eps
    )

    best_threshold = torch.argmax(f_beta).item() / max(num_thresholds - 1, 1)

    return {
        "loss": state["loss_sum"] / max(state["loss_count"], 1),
        "iou": state["iou_sum"] / count,
        "f": f_beta.max().item(),
        "mae": state["mae_sum"] / count,
        "best_threshold": best_threshold,
    }


test_p2 = evaluate_head(model, test_loader, head_idx=head_idx, desc="Final Test")

print(
    f"[Final Test p{head_idx}] "
    f"IoU={test_p2['iou']:.4f} "
    f"F={test_p2['f']:.4f} "
    f"MAE={test_p2['mae']:.4f} "
    f"loss={test_p2['loss']:.4f} "
    f"best_threshold={test_p2['best_threshold']:.4f}",
    flush=True,
)

import os
import random
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F

head_idx = 2
threshold = 0.5

if val_loader is not None and os.path.exists(os.path.join(save_dir, "best_model.pth")):
    eval_path = os.path.join(save_dir, "best_model.pth")
else:
    eval_path = os.path.join(save_dir, "last_model.pth")

print(f"Loading checkpoint for p{head_idx} visualization: {eval_path}")

ckpt = torch.load(eval_path, map_location=device)
model.load_state_dict(ckpt["model_state_dict"])
model.eval()

vis_dir = os.path.join(save_dir, f"visualizations_p{head_idx}")
os.makedirs(vis_dir, exist_ok=True)

mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

indices = random.sample(range(len(test_dataset)), 10)

for n, idx in enumerate(indices, start=1):
    image, mask = test_dataset[idx]

    with torch.no_grad():
        x = image.unsqueeze(0).to(device)
        preds = model(x)

        logits = F.interpolate(
            preds[head_idx],
            size=mask.shape[-2:],
            mode="bilinear",
            align_corners=False,
        )

        prob = torch.softmax(logits, dim=1)[0, 1].cpu().numpy()

    img = (image.cpu() * std + mean).clamp(0, 1)
    img = img.permute(1, 2, 0).numpy()

    gt = mask.cpu().numpy()
    pred = (prob >= threshold).astype(np.uint8)

    overlay = img.copy()
    overlay[..., 0] = np.maximum(overlay[..., 0], pred * 1.0)

    fig, axes = plt.subplots(1, 5, figsize=(20, 4))

    axes[0].imshow(img)
    axes[0].set_title("Image")
    axes[0].axis("off")

    axes[1].imshow(gt, cmap="gray", vmin=0, vmax=1)
    axes[1].set_title("GT")
    axes[1].axis("off")

    axes[2].imshow(prob, cmap="gray", vmin=0, vmax=1)
    axes[2].set_title(f"Pred Prob p{head_idx}")
    axes[2].axis("off")

    axes[3].imshow(pred, cmap="gray", vmin=0, vmax=1)
    axes[3].set_title(f"Pred Mask p{head_idx} @0.5")
    axes[3].axis("off")

    axes[4].imshow(overlay)
    axes[4].set_title("Overlay")
    axes[4].axis("off")

    plt.tight_layout()

    out_path = os.path.join(vis_dir, f"sample_{n}.png")
    plt.savefig(out_path, dpi=150, bbox_inches="tight")
    plt.show()

    print(f"saved: {out_path}")